### ISSUE TITLE
Email for the code but no reply

### ISSUE THREAD

**Issue by xyfffff** [h4duan/contrastive-sat#2]
Hello, Haonan

I've emailed regarding the source code but haven't received a reply. Could you please share it with me at [yfxia@smail.nju.edu.cn](mailto:yfxia@smail.nju.edu.cn) ? It would be greatly appreciated for my work.

Thank you,
Yifan

**Comment by h4duan** [comment]
sent!

**Comment by xyfffff** [comment]
Thank you very much for sharing the code. I appreciate your help!
